kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: vllm-cpu
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/modelServingSupport: '["single"]'
objects:
  - apiVersion: serving.kserve.io/v1alpha1
    kind: ServingRuntime
    metadata:
      name: vllm-cpu
      labels:
        name: vllm-cpu
      annotations:
        opendatahub.io/accelerator-name: ""
        opendatahub.io/apiProtocol: REST
        opendatahub.io/recommended-accelerators: ""
        opendatahub.io/template-display-name: CUSTOM - vLLM Serving Runtime for CPU
        opendatahub.io/template-name: vllm-cpu
        openshift.io/display-name: CUSTOM - vLLM CPU
    spec:
      builtInAdapter:
        modelLoadingTimeoutMillis: 90000
      containers:
        - args:
            - --model
            - /mnt/models
            - --port
            - "8080"
            - --max-model-len
            - "2048"
          image: quay.io/rh-aiservices-bu/vllm-cpu-openai-ubi9:0.3
          name: kserve-container
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
      multiModel: false
      supportedModelFormats:
        - autoSelect: true
          name: vLLM